const assets = [];
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 0, y: -10, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/arrow.obj", "mapFiles/arrow.mtl", { x: -3, y: 0, z: -3 }, 5));
assets.push(new Asset(scene, "mapFiles/mushrooms.obj", "mapFiles/mushrooms.mtl", { x: 3, y: 0, z: 3 }, 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 3, y: -8, z: -15 }, 5));
assets.push(new Asset(scene, "mapFiles/tree-pine.obj", "mapFiles/tree-pine.mtl", { x: 3, y: 2, z: -15 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large.obj", "mapFiles/block-grass-overhang-large.mtl", { x: 13, y: -6, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/rocks.obj", "mapFiles/rocks.mtl", { x: 12, y: -1, z: -3 }, 3, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 30, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-long.obj", "mapFiles/block-grass-overhang-long.mtl", { x: 22, y: -8, z: -10 }, 5));
assets.push(new Asset(scene, "mapFiles/flowers-tall.obj", "mapFiles/flowers-tall.mtl", { x: 22, y: -3, z: -10 }, 5));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 30, y: -6, z: 0 }, 2, true));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 30, y: -6, z: -1.5 }, 2, true));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 30, y: -6, z: -3 }, 2, true));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 30, y: -6, z: 1.5 }, 2, true));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 30, y: -6, z: 3 }, 2, true));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 37, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 42, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 47, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 54.5, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-low-narrow.obj", "mapFiles/block-grass-overhang-low-narrow.mtl", { x: 65.5, y: -9, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-low-narrow.obj", "mapFiles/block-grass-overhang-low-narrow.mtl", { x: 73.5, y: -9, z: 0 }, 3));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-low-narrow.obj", "mapFiles/block-grass-overhang-low-narrow.mtl", { x: 81.5, y: -9, z: 0 }, 4));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 92.5, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/fence-low-straight.obj", "mapFiles/fence-low-straight.mtl", { x: 92.5, y: -6, z: 1.5 }, 5));
assets.push(new Asset(scene, "mapFiles/fence-low-straight.obj", "mapFiles/fence-low-straight.mtl", { x: 92.5, y: -6, z: -4.5 }, 5));
assets.push(new Asset(scene, "mapFiles/trap-spikes.obj", "mapFiles/trap-spikes.mtl", { x: 92.5, y: -6, z: 0 }, 2, true));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-low-long.obj", "mapFiles/block-snow-overhang-low-long.mtl", { x: 73, y: -9, z: -10 }, 5));
assets.push(new Asset(scene, "mapFiles/chest.obj", "mapFiles/chest.mtl", { x: 73, y: -6.5, z: -10 }, 5));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 101, y: -10, z: 0 }, 3, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-narrow.obj", "mapFiles/block-snow-overhang-narrow.mtl", { x: 105, y: -10, z: 0 }, 3));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 109, y: -10, z: 0 }, 3, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-narrow.obj", "mapFiles/block-snow-overhang-narrow.mtl", { x: 113, y: -10, z: 0 }, 3));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 117, y: -10, z: 0 }, 3, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-long.obj", "mapFiles/block-snow-overhang-long.mtl", { x: 123, y: -10, z: 0 }, 3));
assets.push(new Asset(scene, "mapFiles/block-snow-overhang-low.obj", "mapFiles/block-snow-overhang-low.mtl", { x: 113, y: -6, z: -8 }, 3));
assets.push(new Asset(scene, "mapFiles/tree-snow.obj", "mapFiles/tree-snow.mtl", { x: 113, y: -5, z: -8 }, 3));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 133, y: -16, z: 0 }, 5, false, 0, true));
assets.push(new Asset(scene, "mapFiles/flag.obj", "mapFiles/flag.mtl", { x: 133, y: -6, z: -3 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-narrow.obj", "mapFiles/block-grass-overhang-narrow.mtl", { x: 144, y: -8, z: 0 }, 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-narrow.obj", "mapFiles/block-grass-overhang-narrow.mtl", { x: 149, y: -7, z: 0 }, 1.5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-narrow.obj", "mapFiles/block-grass-overhang-narrow.mtl", { x: 154, y: -8, z: 0 }, 2.5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-narrow.obj", "mapFiles/block-grass-overhang-narrow.mtl", { x: 159, y: -7, z: 0 }, 1.5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-narrow.obj", "mapFiles/block-grass-overhang-narrow.mtl", { x: 164, y: -8, z: 0 }, 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 175, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large.obj", "mapFiles/block-grass-overhang-low-large.mtl", { x: 164.5, y: -8.5, z: -30 }, 5));
assets.push(new Asset(scene, "mapFiles/tree.obj", "mapFiles/tree.mtl", { x: 164.5, y: -3.5, z: -30 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-low-long.obj", "mapFiles/block-grass-overhang-low-long.mtl", { x: 143.5, y: -7, z: -15 }, 5));
assets.push(new Asset(scene, "mapFiles/grass.obj", "mapFiles/grass.mtl", { x: 143.5, y: -4.5, z: -15 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/crate.obj", "mapFiles/crate.mtl", { x: 176.2, y: -6, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/crate.obj", "mapFiles/crate.mtl", { x: 178.7, y: -6, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/crate.obj", "mapFiles/crate.mtl", { x: 178.7, y: -3.5, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/crate.obj", "mapFiles/crate.mtl", { x: 178.7, y: -6, z: 2.5 }, 5));
assets.push(new Asset(scene, "mapFiles/crate.obj", "mapFiles/crate.mtl", { x: 178.7, y: -6, z: -2.5 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-low-long.obj", "mapFiles/block-grass-overhang-low-long.mtl", { x: 188, y: -3, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 188, y: -1, z: 0 }, 2, true));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-low-long.obj", "mapFiles/block-grass-overhang-low-long.mtl", { x: 200, y: -3, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 200, y: -1, z: 0 }, 2, true));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block.mtl", { x: 194, y: -1, z: 0 }, 2, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-low-long.obj", "mapFiles/block-grass-overhang-low-long.mtl", { x: 212, y: -3, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 212, y: -1, z: 0 }, 2, true));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block.mtl", { x: 206, y: -1, z: 0 }, 2, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 200, y: -12, z: -35 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-low-long.obj", "mapFiles/block-grass-overhang-low-long.mtl", { x: 230, y: 0, z: -20 }, 5));
assets.push(new Asset(scene, "mapFiles/plant.obj", "mapFiles/plant.mtl", { x: 202, y: -7, z: -36 }, 5));
assets.push(new Asset(scene, "mapFiles/plant.obj", "mapFiles/plant.mtl", { x: 198, y: -7, z: -34 }, 5));
assets.push(new Asset(scene, "mapFiles/poles.obj", "mapFiles/poles.mtl", { x: 230, y: 0, z: -20 }, 5));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 225, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 230, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 235, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 240, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 245, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 250, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 255, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 260, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 265, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/platform.obj", "mapFiles/platform.mtl", { x: 270, y: -8, z: 0 }, 5, false, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 233, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 233, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 243, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 243, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 238, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 238, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 235.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 240.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 245.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 249.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/trap-spikes-large.obj", "mapFiles/trap-spikes-large.mtl", { x: 249.5, y: -7, z: 0 }, 4, true));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 253.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 256, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 256, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 261, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 261, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 266, y: -7, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/spike-block-wide.obj", "mapFiles/spike-block-wide.mtl", { x: 266, y: 2, z: 0 }, 1.5, true, Math.PI / 2));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 274, y: -16, z: 0 }, 5));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 258.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/spike-block.obj", "mapFiles/spike-block.mtl", { x: 263.5, y: 0, z: 0 }, 1.5, true));
assets.push(new Asset(scene, "mapFiles/mushrooms.obj", "mapFiles/mushrooms.mtl", { x: 222, y: -6, z: 3 }, 3));
assets.push(new Asset(scene, "mapFiles/block-grass-overhang-large-tall.obj", "mapFiles/block-grass-overhang-large-tall.mtl", { x: 249.5, y: -8, z: -16 }, 4));
assets.push(new Asset(scene, "mapFiles/tree-pine.obj", "mapFiles/tree-pine.mtl", { x: 249.5, y: 0, z: -16 }, 5));
assets.push(new Asset(scene, "mapFiles/door-large-open.obj", "mapFiles/door-large-open.mtl", { x: 274, y: -6, z: 0 }, 10, false, Math.PI / 2, false, true));